name: Go services build and test.
on:
  push:
    branches: [ "main" ]
    paths: 
      - "user-service/**"
      - "task-service/**"
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build user-service
      working-directory: "user-service"
      run: go build -v ./...

    - name: Test user-service
      working-directory: "user-service"
      run: go test -v ./...

    - name: Build task-service 
      working-directory: "task-service"
      run: go build -v ./...

    - name: Test task-service
      working-directory: "task-service"
      run: go test -v ./...
